const SITE_URL = 'https://doctarx.com';

export default function robots() {
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/ng',
          '/ng/provider/register',
          '/ng/pharmacy/onboarding',
          '/ng/patient/search',
          '/ng/patient/track',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/patient/dashboard/',
          '/patient/appointments/',
          '/patient/triage/',
          '/patient/prescriptions/',
          '/patient/records/',
          '/patient/messages/',
          '/patient/notifications/',
          '/patient/billing/',
          '/patient/pharmacy/',
          '/patient/wallet/',
          '/patient/subscription/',
          '/patient/profile/',
          '/patient/settings/',
          '/provider/dashboard/',
          '/provider/triage-queue/',
          '/provider/triage/',
          '/provider/prescriptions/',
          '/provider/call/',
          '/provider/imaging/',
          '/provider/schedule/',
          '/provider/patients/',
          '/provider/visits/',
          '/provider/claims/',
          '/provider/referrals/',
          '/provider/hospital-network/',
          '/provider/analytics/',
          '/provider/messages/',
          '/provider/notifications/',
          '/provider/profile/',
          '/provider/credentialing/',
          '/provider/settings/',
          '/ng/admin/',
          '/ng/auth/',
          '/ng/patient/appointments/',
          '/ng/patient/call/',
          '/ng/patient/messages/',
          '/ng/patient/notifications/',
          '/ng/patient/orders/',
          '/ng/patient/prescriptions/',
          '/ng/patient/profile/',
          '/ng/patient/records/',
          '/ng/patient/settings/',
          '/ng/provider/analytics/',
          '/ng/provider/appointments/',
          '/ng/provider/call/',
          '/ng/provider/claims/',
          '/ng/provider/credentialing/',
          '/ng/provider/dashboard/',
          '/ng/provider/encounters/',
          '/ng/provider/hospital-network/',
          '/ng/provider/imaging/',
          '/ng/provider/login/',
          '/ng/provider/messages/',
          '/ng/provider/notifications/',
          '/ng/provider/patients/',
          '/ng/provider/prescriptions/',
          '/ng/provider/profile/',
          '/ng/provider/referrals/',
          '/ng/provider/schedule/',
          '/ng/provider/settings/',
          '/ng/provider/triage/',
          '/ng/provider/triage-queue/',
          '/ng/provider/visits/',
          '/ng/pharmacy/dashboard/',
          '/ng/pharmacy/inventory/',
          '/ng/pharmacy/login/',
          '/ng/pharmacy/notifications/',
          '/ng/pharmacy/orders/',
          '/ng/pharmacy/profile/',
          '/ng/pharmacy/register/',
          '/ng/pharmacy/settings/',
          '/ng/pharmacy/wallet/',
          '/secure/admin',
          '/_next/',
          '/test-payment/',
          '/forgot-password/',
          '/reset-password/',
          '/verify-email/',
        ],
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
