import {
  Activity,
  Banknote,
  Building2,
  Calendar,
  CheckCircle,
  Clock,
  CreditCard,
  Lock,
  MapPin,
  Package,
  Phone,
  Pill,
  Search,
  ShieldCheck,
  Stethoscope,
  Truck,
  User,
  Video,
} from 'lucide-react';

export const MARKET_HOME_DATA = {
  US: {
    code: 'US',
    name: 'United States',
    showCountrySelector: false,
    otherMarket: {
      href: '/ng',
      label: 'DoctaRx Nigeria',
    },
    marketBridge: {
      badge: 'Nigeria operations',
      title: 'Looking for DoctaRx Nigeria?',
      description:
        'Stakeholders, providers, pharmacies, and patients in Nigeria should use DoctaRx Nigeria at doctarx.com/ng for online doctor consultations, prescription upload, medicine search, pharmacy onboarding, and local payment workflows.',
      primaryCta: {
        label: 'Visit DoctaRx Nigeria',
        href: '/ng',
      },
      secondaryCta: {
        label: 'Nigeria Provider Registration',
        href: '/ng/provider/register',
      },
      points: [
        'Online doctor consultation and prescription follow-through in Nigeria.',
        'Medicine search, partner pharmacy coordination, and local payment rails.',
        'Dedicated Nigeria provider and pharmacy onboarding paths.',
      ],
    },
    banner: {
      emergencyNumber: '911',
      emergencyLabel: 'Medical emergency? Call',
      emergencyTail: 'or go to the nearest emergency room immediately.',
    },
    navLinks: [
      { label: 'How It Works', href: '#workflow' },
      { label: 'Specialists', href: '#features' },
      { label: 'Pharmacy', href: '#network' },
      { label: 'Security', href: '#security' },
    ],
    loginItems: [
      {
        label: 'Patient Portal',
        description: 'Visits, messages, prescriptions',
        href: '/patient/login',
        icon: User,
        tone: 'blue',
      },
      {
        label: 'Provider Portal',
        description: 'Schedules, charting, follow-up care',
        href: '/provider/login',
        icon: Stethoscope,
        tone: 'emerald',
      },
      {
        label: 'Pharmacy Portal',
        description: 'Prescription fulfillment and updates',
        href: '/pharmacy/login',
        icon: Pill,
        tone: 'violet',
      },
    ],
    getStartedItems: [
      {
        label: 'Patient',
        description: 'Start virtual care',
        href: '/patient/register',
        icon: User,
        tone: 'blue',
      },
      {
        label: 'Provider',
        description: 'Join the clinical network',
        href: '/provider/register',
        icon: Stethoscope,
        tone: 'emerald',
      },
      {
        label: 'Pharmacy',
        description: 'Connect prescription workflows',
        href: '/pharmacy/register',
        icon: Pill,
        tone: 'violet',
      },
    ],
    hero: {
      badge: '24/7 specialist access across the US',
      title: 'Quality healthcare,',
      highlight: 'right in your pocket.',
      description:
        'Consult with board-certified doctors from home, receive digital prescriptions, and keep pharmacy delivery or lab follow-through moving without a waiting room.',
      primaryCta: {
        label: 'Book a Consultation',
        href: '/patient/register',
      },
      secondaryCta: {
        label: 'Explore Specialists',
        href: '#features',
      },
      tertiaryCta: {
        label: 'View Plans',
        href: '#pricing',
      },
      trustItems: [
        { icon: Video, text: '24/7 virtual care' },
        { icon: Stethoscope, text: 'Board-certified clinicians' },
        { icon: Pill, text: 'Digital prescriptions' },
        { icon: Building2, text: 'Pharmacy and labs' },
      ],
      visualTone: 'emerald',
      visual: {
        title: 'At-home care journey',
        subtitle: 'Board-certified telehealth, digital prescriptions, and doorstep-ready follow-through in one polished US flow.',
        chips: ['24/7 specialists', 'Digital Rx', 'Pharmacy and labs'],
        metric: {
          value: 'At-home specialist access',
          label: 'Virtual consultations, prescriptions, and next-step coordination stay visible from the same US telehealth front door.',
        },
        tiles: [
          {
            title: 'Virtual consult',
            body: 'Patients can connect with a specialist from home instead of waiting on an in-person schedule.',
            tone: 'blue',
          },
          {
            title: 'Digital prescription',
            body: 'Medication details stay on the patient device immediately after the visit ends.',
            tone: 'emerald',
          },
          {
            title: 'Pharmacy and labs',
            body: 'Delivery coordination and testing follow-through remain visible after the consultation.',
            tone: 'amber',
          },
        ],
        railTitle: 'From consult to follow-through',
        railSummary: 'Doctor access, prescriptions, and home delivery or lab coordination stay connected instead of fragmenting across separate services.',
        railItems: [
          'Book a specialist without the commute',
          'Receive a verified digital prescription after the visit',
          'Keep pharmacy delivery or lab next steps visible at home',
        ],
      },
    },
    stats: [
      { icon: Video, value: '24/7 access', label: 'board-certified care without the waiting room' },
      { icon: ShieldCheck, value: 'HIPAA-ready', label: 'protected visits, messaging, and records' },
      { icon: Pill, value: 'Digital Rx', label: 'prescriptions stay on the patient device' },
      { icon: Building2, value: 'Pharmacy and labs', label: 'follow-through stays connected after the visit' },
    ],
    featureSection: {
      badge: 'US care journey',
      title: 'Complete care, from consult to pharmacy follow-through.',
      subtitle:
        'The US homepage now uses real imagery to tell the care story: start the consultation, receive the prescription, and keep delivery or testing in view.',
    },
    features: [
      {
        icon: Video,
        tone: 'blue',
        preview: 'dashboard',
        title: 'Instant consultations',
        description: 'Meet with licensed US physicians and specialists over HD video or secure chat from home.',
        points: ['HD video or chat', 'No waiting room commute'],
      },
      {
        icon: Pill,
        tone: 'emerald',
        preview: 'shield',
        title: 'Digital prescriptions',
        description: 'Receive a verified digital prescription after the visit and keep medication instructions easy to revisit on your phone.',
        points: ['Mobile-friendly prescription access', 'Clear post-visit medication guidance'],
      },
      {
        icon: Building2,
        tone: 'amber',
        preview: 'delivery',
        title: 'Pharmacy and lab coordination',
        description: 'Prescription routing, delivery coordination, and lab follow-through stay connected after the consultation instead of disappearing into a handoff.',
        points: ['Delivery-ready fulfillment', 'Lab and pharmacy next-step visibility'],
      },
      {
        icon: ShieldCheck,
        tone: 'violet',
        preview: 'network',
        title: 'Family-ready trust',
        description: 'HIPAA-ready messaging, protected records, and flexible care access support families balancing work, school, and ongoing care.',
        points: ['HIPAA-ready workflows', 'Care continuity for households'],
      },
    ],
    workflowSection: {
      title: 'How care fits an American routine',
      subtitle: 'Book from home, talk to a doctor, receive a digital prescription, and keep pharmacy or lab next steps moving without breaking your day.',
    },
    workflowSteps: [
      {
        icon: User,
        title: 'Create your account',
        description: 'Start as a patient, provider, or pharmacy partner with role-specific onboarding paths.',
      },
      {
        icon: Video,
        title: 'Meet a specialist',
        description: 'Join a secure consultation from home and move straight into the next care decision.',
      },
      {
        icon: Pill,
        title: 'Receive the prescription',
        description: 'Medication instructions and verified digital prescription details stay available right after the visit.',
      },
      {
        icon: Building2,
        title: 'Complete follow-through',
        description: 'Move into pharmacy delivery or lab coordination without losing the context of the original consultation.',
      },
    ],
    audienceSection: {
      id: 'network',
      badge: 'Audience Paths',
      title: 'Built for patients, providers, and fulfillment teams.',
      subtitle: 'Each role gets a clear entry point and a premium interface without confusing cross-market language.',
    },
    audienceCards: [
      {
        icon: User,
        tone: 'blue',
        title: 'Patients',
        description: 'Register, talk to a doctor, manage prescriptions, and keep follow-up moving from one account.',
        bullets: ['Book care without the commute', 'Visits, messaging, and prescriptions in one place'],
        ctaLabel: 'Create Patient Account',
        ctaHref: '/patient/register',
      },
      {
        icon: Stethoscope,
        tone: 'emerald',
        title: 'Providers',
        description: 'Access schedules, clinical workflows, and secure telehealth tools inside the provider workspace.',
        bullets: ['Clinical workflow access', 'Virtual visit and follow-up continuity'],
        ctaLabel: 'Provider Access',
        ctaHref: '/provider/login',
      },
      {
        icon: Pill,
        tone: 'violet',
        title: 'Pharmacies and operations',
        description: 'Prescription routing and fulfillment visibility remain connected to the rest of the care journey.',
        bullets: ['Prescription queue visibility', 'Delivery and lab handoff support'],
        ctaLabel: 'Pharmacy Portal',
        ctaHref: '/pharmacy/login',
      },
    ],
    pricingSection: {
      title: 'Membership options already present in the product',
      subtitle: 'US pricing stays in dollars only, and the section reflects existing subscription tiers instead of placeholder values.',
      note: 'Pay-per-visit and insurance-supported scheduling remain available in the booking flow.',
    },
    plans: [
      {
        eyebrow: 'Docta Basic',
        title: '$19.99',
        period: '/month',
        description: 'Essentials for ongoing care and messaging.',
        tone: 'blue',
        featured: false,
        features: [
          'Unlimited messaging with providers',
          '2 telehealth consultations per month',
          'Prescription access',
          'Health records access',
        ],
        ctaLabel: 'Choose Basic',
        ctaHref: '/patient/register',
      },
      {
        eyebrow: 'Docta Gold',
        title: '$39.99',
        period: '/month',
        description: 'Unlimited consultations with priority access.',
        tone: 'emerald',
        featured: true,
        features: [
          'Unlimited video consultations',
          'Prescription access',
          'Priority support',
          '24/7 urgent care access',
        ],
        ctaLabel: 'Choose Gold',
        ctaHref: '/patient/register',
      },
      {
        eyebrow: 'Docta Platinum',
        title: '$79.99',
        period: '/month',
        description: 'Premium care coordination for ongoing support.',
        tone: 'violet',
        featured: false,
        features: [
          'All Gold features',
          'Dedicated care coordinator',
          'Family coverage for up to 4 members',
          'Premium membership card',
        ],
        ctaLabel: 'Choose Platinum',
        ctaHref: '/patient/register',
      },
    ],
    securitySection: {
      badge: 'Clinical Trust Layer',
      title: 'Protected care, digital prescriptions, and follow-up clarity stay visible.',
      description:
        'The US homepage now speaks to secure telehealth, HIPAA-ready messaging, and prescription follow-through with imagery that matches the care story.',
      bullets: [
        'HIPAA-ready video and messaging',
        'Protected records and role-aware access',
        'Digital prescription and pharmacy handoff visibility',
        'Family-ready follow-up care',
      ],
    },
    cta: {
      title: 'See a doctor before the waiting room would open.',
      description:
        'Patients can book care in minutes, consult from home, and move from digital prescription to pharmacy or lab follow-through in the same interface language.',
      primary: {
        label: 'Book Care Now',
        href: '/patient/register',
      },
      secondary: {
        label: 'View Plans',
        href: '#pricing',
      },
    },
    footer: {
      description:
        'Board-certified virtual care, digital prescriptions, and pharmacy follow-through for the US telehealth experience.',
      email: 'info@doctarx.com',
      homeHref: '/',
      columns: [
        {
          title: 'Patients',
          links: [
            { label: 'Book Consultation', href: '/patient/register' },
            { label: 'How It Works', href: '/#workflow' },
            { label: 'Plans', href: '/#pricing' },
            { label: 'Patient Login', href: '/patient/login' },
          ],
        },
        {
          title: 'Providers',
          links: [
            { label: 'Join as Provider', href: '/provider/register' },
            { label: 'Provider Login', href: '/provider/login' },
            { label: 'Security', href: '/hipaa' },
          ],
        },
        {
          title: 'Operations',
          links: [
            { label: 'Pharmacy Portal', href: '/pharmacy/login' },
            { label: 'DoctaRx Nigeria', href: '/ng' },
            { label: 'Nigeria Provider Registration', href: '/ng/provider/register' },
            { label: 'Contact', href: '/contact' },
          ],
        },
        {
          title: 'Legal',
          links: [
            { label: 'Privacy', href: '/privacy' },
            { label: 'Terms', href: '/terms' },
            { label: 'Accessibility', href: '/accessibility' },
            { label: 'FAQ', href: '/faq' },
          ],
        },
      ],
      badges: [
        { icon: ShieldCheck, label: 'Secure workflows' },
        { icon: Lock, label: 'Encrypted messaging' },
        { icon: Pill, label: 'E-prescribing' },
      ],
      copyright: 'DoctaRx',
    },
  },
  NG: {
    code: 'NG',
    name: 'Nigeria',
    showCountrySelector: false,
    otherMarket: {
      href: '/',
      label: 'DoctaRx United States',
    },
    banner: {
      emergencyNumber: '112',
      emergencyLabel: 'Medical emergency? Call',
      emergencyTail: 'or go to the nearest hospital immediately.',
    },
    navLinks: [
      { label: 'Care', href: '#features' },
      { label: 'Workflow', href: '#workflow' },
      { label: 'Access & Payment', href: '#pricing' },
      { label: 'Trust', href: '#security' },
    ],
    loginItems: [
      {
        label: 'Patient Portal',
        description: 'Consultations, prescriptions, and orders',
        href: '/ng/patient/login',
        icon: User,
        tone: 'emerald',
      },
      {
        label: 'Provider Portal',
        description: 'Clinical workspace and video visits',
        href: '/ng/provider/login',
        icon: Stethoscope,
        tone: 'blue',
      },
      {
        label: 'Pharmacy Portal',
        description: 'Login, register, or learn pharmacy partnership',
        href: '/ng/pharmacy',
        icon: Pill,
        tone: 'violet',
      },
    ],
    getStartedItems: [
      {
        label: 'Patients: Register Free',
        description: 'Pay only when booking consultation',
        href: '/ng/patient/register',
        icon: User,
        tone: 'emerald',
      },
      {
        label: 'Search Medicines',
        description: 'Compare trusted pharmacy options',
        href: '/ng/medicines',
        tone: 'blue',
        icon: Search,
      },
      {
        label: 'Providers: Start 1 Month Free',
        description: 'Use DoctaRx tools during trial',
        href: '/ng/provider/register',
        icon: Stethoscope,
        tone: 'slate',
      },
      {
        label: 'Pharmacies: Join the Network',
        description: 'Register and set prescription intake',
        href: '/ng/pharmacy',
        icon: Pill,
        tone: 'violet',
      },
    ],
    hero: {
      badge: 'Nigeria telehealth access',
      title: 'Quality healthcare,',
      highlight: 'right in your pocket.',
      description:
        'Patients register free and pay only when booking a consultation, unless covered by an organisation. Providers can start with one month free access, and pharmacies can join the DoctaRx Nigeria network.',
      primaryCta: {
        label: 'Patients: Register Free',
        href: '/ng/patient/register',
      },
      secondaryCta: {
        label: 'Providers: Start 1 Month Free',
        href: '/ng/provider/register',
      },
      tertiaryCta: {
        label: 'View Plans',
        href: '/ng/pricing',
      },
      trustItems: [
        { icon: User, text: 'Patients register free' },
        { icon: CreditCard, text: 'Pay per consultation' },
        { icon: Stethoscope, text: 'Providers get 1 month free' },
        { icon: Pill, text: 'Pharmacies onboard free' },
      ],
      visualTone: 'emerald',
      visual: {
        title: 'Nigeria care journey',
        subtitle: 'Consultations, prescriptions, payment, and pharmacy handoff stay clear on every device.',
        chips: ['Online doctor', 'Prescription upload', 'Transfer, card, USSD'],
        metric: {
          value: 'Care that feels local',
          label: 'Doctor review, prescription handling, and medicine access stay connected inside one trusted flow.',
        },
        tiles: [
          {
            title: 'Doctor consultation',
            body: 'Patients can start with an online consultation before moving straight into prescriptions and follow-up.',
            tone: 'emerald',
          },
          {
            title: 'Prescription review',
            body: 'Upload a prescription once and keep provider review, pharmacy confirmation, and status updates in view.',
            tone: 'blue',
          },
          {
            title: 'Pickup or delivery',
            body: 'Partner pharmacies confirm availability, pricing, and fulfillment without sending patients into a generic checkout.',
            tone: 'violet',
          },
        ],
        railTitle: 'Care and pharmacy checkpoints',
        railSummary: 'The experience stays fast on mobile while still feeling clinical, premium, and unmistakably Nigerian.',
        railItems: [
          'Consultation and prescription review stay in one patient journey',
          'Partner pharmacies confirm availability before payment',
          'Pickup or delivery updates remain visible after checkout',
        ],
      },
    },
    stats: [
      { icon: Video, value: 'Doctor consults', label: 'start care from the same platform' },
      { icon: Search, value: 'Medicine search', label: 'check partner pharmacy availability' },
      { icon: CreditCard, value: 'Local payment', label: 'transfer, card, and USSD support' },
      { icon: Truck, value: 'Fulfillment updates', label: 'pickup or delivery stays visible' },
    ],
    featureSection: {
      badge: 'Regional Experience',
      title: 'A premium Nigeria experience built for real care delivery.',
      subtitle:
        'The product stays visually polished while speaking clearly to online doctor consultations, prescriptions, pharmacy confirmation, and local payment behavior.',
    },
    features: [
      {
        icon: Video,
        tone: 'emerald',
        preview: 'checkout',
        title: 'Online doctor consultations',
        description: 'Patients can begin with a consultation and move into prescription follow-up without leaving the Nigeria experience.',
        points: ['Provider-ready flow', 'Secure telehealth path'],
      },
      {
        icon: Package,
        tone: 'blue',
        preview: 'pharmacy',
        title: 'Prescription review and upload',
        description: 'Medication requests, uploaded prescriptions, and provider recommendations stay readable instead of becoming a wall of copy.',
        points: ['Upload once', 'Provider and pharmacy review'],
      },
      {
        icon: Building2,
        tone: 'violet',
        preview: 'delivery',
        title: 'Verified pharmacy coordination',
        description: 'Partner pharmacies confirm stock, substitutions, and pricing inside a workflow designed for Nigeria operations.',
        points: ['Availability checks', 'Trusted handoff'],
      },
      {
        icon: CreditCard,
        tone: 'amber',
        preview: 'wallet',
        previewLabels: ['Card', 'Transfer', 'USSD', 'Pickup'],
        title: 'Local payment rails',
        description: 'Payment language stays local, while pickup and delivery updates remain clear after checkout.',
        points: ['Transfer, card, and USSD', 'Pickup or delivery updates'],
      },
    ],
    workflowSection: {
      title: 'How care moves through DoctaRx Nigeria',
      subtitle: 'The path is simpler to scan: start care, confirm the prescription, pay locally, and keep fulfillment visible on mobile.',
    },
    workflowSteps: [
      {
        icon: Video,
        title: 'Start with care',
        description: 'Create an account, join an online consultation, or begin with a medicine search from the same homepage.',
      },
      {
        icon: Package,
        title: 'Share the prescription',
        description: 'Prescriptions, provider review, and medication requests stay connected instead of splitting across separate portals.',
      },
      {
        icon: Building2,
        title: 'Confirm the pharmacy',
        description: 'Partner pharmacies verify stock, pricing, and substitutions before the order moves forward.',
      },
      {
        icon: CreditCard,
        title: 'Pay and follow delivery',
        description: 'Transfer, card, and USSD checkout stays readable, with pickup or delivery status visible after payment.',
      },
    ],
    audienceSection: {
      id: 'network',
      badge: 'Nigeria Network',
      title: 'Built for patients, clinicians, and pharmacy teams.',
      subtitle: 'Each path feels local, trusted, and ready for real healthcare delivery.',
    },
    audienceCards: [
      {
        icon: User,
        tone: 'emerald',
        title: 'Patients',
        description: 'Register free, keep a patient portal account, and pay only when booking a consultation unless an organisation covers the visit.',
        bullets: ['Free patient registration', 'Pay per consultation or use organisation coverage'],
        ctaLabel: 'Patients: Register Free',
        ctaHref: '/ng/patient/register',
      },
      {
        icon: Pill,
        tone: 'violet',
        title: 'Pharmacies',
        description: 'Join the DoctaRx network to receive prescriptions, confirm availability, and serve patients through dashboard or WhatsApp-assisted operations.',
        bullets: ['Free pharmacy onboarding', 'Dashboard and WhatsApp intake options'],
        ctaLabel: 'Pharmacies: Join the Network',
        ctaHref: '/ng/pharmacy',
      },
      {
        icon: Stethoscope,
        tone: 'blue',
        title: 'Clinicians',
        description: 'Providers can sign up and use DoctaRx tools free for one month while onboarding and building their Nigeria telehealth workflow.',
        bullets: ['One-month provider trial', 'Trial status and usage tracked in the portal'],
        ctaLabel: 'Providers: Start 1 Month Free',
        ctaHref: '/ng/provider/register',
      },
      {
        icon: Building2,
        tone: 'amber',
        title: 'Organisations',
        description: 'Companies, schools, churches, NGOs, and associations can request bulk plans to cover employees, members, or communities.',
        bullets: ['Bulk employee or member coverage', 'Admin-confirmed billing and renewal paths'],
        ctaLabel: 'Organizations: Cover Your Team',
        ctaHref: '/ng/organization/register',
      },
    ],
    pricingSection: {
      mode: 'access',
      tabLabel: 'Access',
      title: 'How access and payment work in the Nigeria flow',
      subtitle:
        'Patients create accounts free, providers start with a one-month free trial, pharmacies onboard free, and organisations can subscribe in bulk for covered members.',
      note: 'Patients are not blocked by a monthly subscription. Consultation fees, medicine pricing, delivery charges, provider subscriptions, and organisation coverage are confirmed through the real workflow.',
      cards: [
        {
          eyebrow: 'Patient access',
          title: 'Register free. Pay when you book.',
          description: 'Patients can create a DoctaRx Nigeria account without a monthly subscription. Payment applies when booking a consultation unless organisation coverage applies.',
          tone: 'emerald',
          features: [
            'Free patient registration',
            'Pay only when booking consultation',
            'Prescription and medicine follow-up in one account',
          ],
          ctaLabel: 'Patients: Register Free',
          ctaHref: '/ng/patient/register',
        },
        {
          eyebrow: 'Provider trial',
          title: 'One month free provider access',
          description: 'Providers can register and start with one month free access to DoctaRx tools. Trial usage and access status are tracked by the platform.',
          tone: 'blue',
          features: [
            'Trial starts after activation/approval',
            'Usage summary and days remaining',
            'Subscription required after trial expiration',
          ],
          ctaLabel: 'Providers: Start 1 Month Free',
          ctaHref: '/ng/provider/register',
        },
        {
          eyebrow: 'Partner network',
          title: 'Pharmacies join free',
          description: 'Pharmacy partners can register, complete onboarding, receive prescription requests, and confirm availability and price before fulfillment.',
          tone: 'violet',
          features: [
            'Pharmacy dashboard and login',
            'WhatsApp receiving preference',
            'Pickup and delivery readiness',
          ],
          ctaLabel: 'Pharmacies: Join the Network',
          ctaHref: '/ng/pharmacy',
        },
        {
          eyebrow: 'Organisation coverage',
          title: 'Cover employees or members',
          description: 'Organisations can request bulk subscription plans for employees, members, communities, or school and faith-based groups.',
          tone: 'amber',
          features: [
            'Bulk care coverage requests',
            'Employee/member enrollment model',
            'Manual invoice and payment confirmation path',
          ],
          ctaLabel: 'Organizations: Cover Your Team',
          ctaHref: '/ng/organization/register',
        },
      ],
      sideTitle: 'What stays visible to patients',
      sideDescription: 'The commercial story is clear: free signup, pay-per-consultation for patients, trial-to-subscription for providers, and bulk coverage for organisations.',
      sideNotes: [
        'Consultation and prescription context stay connected',
        'Partner pharmacies confirm stock before payment',
        'Pickup or delivery status remains visible after checkout',
      ],
    },
    plans: [],
    securitySection: {
      badge: 'Compliance and Trust',
      title: 'Clinical trust and local payment clarity stay visible.',
      description:
        'DoctaRx Nigeria combines online consultations, prescription verification, NDPA-aware handling, and trusted pharmacy coordination without generic Western-only messaging.',
      bullets: [
        'NDPA-aware data handling',
        'Prescription verification and provider review',
        'Transfer, card, and USSD payment language',
        'Order and delivery status visibility',
      ],
    },
    cta: {
      title: 'Start care or medicine access without switching platforms.',
      description:
        'Patients register free, providers can start one month free, pharmacies can join the network, and organisations can request bulk coverage for their people.',
      primary: {
        label: 'Patients: Register Free',
        href: '/ng/patient/register',
      },
      secondary: {
        label: 'Search Medicines',
        href: '/ng/medicines',
      },
    },
    footer: {
      description:
        'DoctaRx Nigeria connects online doctor care, prescriptions, pharmacy coordination, and medicine fulfillment in one trusted platform.',
      email: 'hello@doctarx.ng',
      homeHref: '/ng',
      columns: [
        {
          title: 'Patients',
          links: [
            { label: 'Register Free', href: '/ng/patient/register' },
            { label: 'Search Medicines', href: '/ng/medicines' },
            { label: 'Sign In', href: '/ng/patient/login' },
          ],
        },
        {
          title: 'Pharmacies',
          links: [
            { label: 'Pharmacy Portal', href: '/ng/pharmacy' },
            { label: 'Pharmacy Login', href: '/ng/pharmacy/login' },
            { label: 'Register Pharmacy', href: '/ng/pharmacy/register' },
            { label: 'Network View', href: '/ng#network' },
            { label: 'Access & Payment', href: '/ng#pricing' },
          ],
        },
        {
          title: 'Compliance',
          links: [
            { label: 'Trust', href: '/ng#security' },
            { label: 'Privacy', href: '/privacy' },
            { label: 'Terms', href: '/terms' },
          ],
        },
        {
          title: 'Operations',
          links: [
            { label: 'Provider Login', href: '/ng/provider/login' },
            { label: 'Start 1 Month Free', href: '/ng/provider/register' },
            { label: 'Organisation Bulk Plans', href: '/ng/organization/register' },
            { label: 'Contact', href: 'mailto:hello@doctarx.ng' },
            { label: 'US Experience', href: '/' },
          ],
        },
      ],
      badges: [
        { icon: ShieldCheck, label: 'Secure workflows' },
        { icon: CreditCard, label: 'Local payment rails' },
        { icon: Video, label: 'Online consultations' },
      ],
      copyright: 'DoctaRx Nigeria',
    },
  },
};
