import {
  Activity,
  Banknote,
  Building2,
  Calendar,
  CheckCircle,
  Clock,
  CreditCard,
  Lock,
  MapPin,
  Package,
  Phone,
  Pill,
  Search,
  ShieldCheck,
  Stethoscope,
  Truck,
  User,
  Video,
} from 'lucide-react';

export const MARKET_HOME_DATA = {
  US: {
    code: 'US',
    name: 'United States',
    showCountrySelector: false,
    otherMarket: null,
    banner: {
      emergencyNumber: '911',
      emergencyLabel: 'Medical emergency? Call',
      emergencyTail: 'or go to the nearest emergency room immediately.',
    },
    navLinks: [
      { label: 'Features', href: '#features' },
      { label: 'How It Works', href: '#workflow' },
      { label: 'Plans', href: '#pricing' },
      { label: 'Security', href: '#security' },
    ],
    loginItems: [
      {
        label: 'Patient Portal',
        description: 'Visits, messages, prescriptions',
        href: '/patient/login',
        icon: User,
        tone: 'blue',
      },
      {
        label: 'Provider Portal',
        description: 'Schedules, charting, follow-up care',
        href: '/provider/login',
        icon: Stethoscope,
        tone: 'emerald',
      },
      {
        label: 'Pharmacy Portal',
        description: 'Prescription fulfillment and updates',
        href: '/pharmacy/login',
        icon: Pill,
        tone: 'violet',
      },
    ],
    getStartedItems: [
      {
        label: 'Patient',
        description: 'Start virtual care',
        href: '/patient/register',
        icon: User,
        tone: 'blue',
      },
      {
        label: 'Provider',
        description: 'Join the clinical network',
        href: '/provider/register',
        icon: Stethoscope,
        tone: 'emerald',
      },
      {
        label: 'Pharmacy',
        description: 'Connect prescription workflows',
        href: '/pharmacy/register',
        icon: Pill,
        tone: 'violet',
      },
    ],
    hero: {
      badge: 'United States telehealth',
      title: 'Telehealth built for modern care teams.',
      highlight: 'Secure visits, connected records, and prescription routing.',
      description:
        'Book virtual consultations, keep insurance information ready, message your care team, and move from intake to follow-up inside one polished care experience.',
      primaryCta: {
        label: 'Start as Patient',
        href: '/patient/register',
      },
      secondaryCta: {
        label: 'Provider Access',
        href: '/provider/login',
      },
      tertiaryCta: {
        label: 'View Plans',
        href: '#pricing',
      },
      trustItems: [
        { icon: ShieldCheck, text: 'HIPAA-ready workflows' },
        { icon: Video, text: 'Secure video visits' },
        { icon: Pill, text: 'E-prescribing' },
        { icon: Building2, text: 'Pharmacy coordination' },
      ],
      visualTone: 'blue',
      visual: {
        title: 'Connected Care Workspace',
        subtitle: 'Intake, appointments, prescriptions, and follow-up in one premium view.',
        chips: ['Secure video', 'Insurance ready', 'Rx routing'],
        metric: {
          value: 'Clinical-grade flow',
          label: 'One interface for patient intake, visit readiness, and post-visit action.',
        },
        tiles: [
          {
            title: 'Visit queue',
            body: 'Upcoming visits, device checks, and triage signals stay visible before the session begins.',
            tone: 'blue',
          },
          {
            title: 'Coverage details',
            body: 'Insurance information and self-pay options are prepared before booking completes.',
            tone: 'emerald',
          },
          {
            title: 'Prescription routing',
            body: 'Medication orders move directly into pharmacy workflows after the visit is signed.',
            tone: 'violet',
          },
        ],
        railTitle: 'Workflow highlights',
        railItems: [
          'Insurance details captured before booking',
          'Secure messaging for follow-up questions',
          'Care plans, prescriptions, and reminders synced after each visit',
        ],
      },
    },
    stats: [
      { icon: ShieldCheck, value: 'HIPAA-ready', label: 'encryption and access controls' },
      { icon: CreditCard, value: 'Insurance + self-pay', label: 'billing paths already built in' },
      { icon: Video, value: 'Virtual visits', label: 'video and messaging care workflows' },
      { icon: Pill, value: 'Rx connected', label: 'prescription handoff to pharmacies' },
    ],
    featureSection: {
      badge: 'Care Platform',
      title: 'A premium US care experience without market leakage.',
      subtitle:
        'The homepage stays focused on the US telehealth product: virtual care, billing readiness, and prescription coordination with clean, market-specific copy.',
    },
    features: [
      {
        icon: Video,
        tone: 'blue',
        preview: 'dashboard',
        title: 'Visit readiness',
        description: 'Patients move from intake to secure video visits with cleaner scheduling and pre-visit preparation.',
        points: ['Pre-visit status', 'Secure audio and video'],
      },
      {
        icon: ShieldCheck,
        tone: 'emerald',
        preview: 'shield',
        title: 'Protected communication',
        description: 'Messaging, notes, and follow-up actions are presented with a compliance-first trust layer.',
        points: ['Encrypted workflow', 'Audit-friendly surfaces'],
      },
      {
        icon: Building2,
        tone: 'violet',
        preview: 'network',
        title: 'Connected care ops',
        description: 'Pharmacy routing, team coordination, and post-visit orchestration stay inside one experience.',
        points: ['Prescription routing', 'Care handoff visibility'],
      },
      {
        icon: CreditCard,
        tone: 'amber',
        preview: 'wallet',
        previewLabels: ['Insurance', 'Card', 'Self-Pay', 'Plan'],
        title: 'Payment flexibility',
        description: 'Insurance and subscription workflows stay visible without pushing the wrong currency or wrong market copy.',
        points: ['Plan-aware entry', 'Self-pay supported'],
      },
    ],
    workflowSection: {
      title: 'How care moves through the product',
      subtitle: 'The desktop, tablet, and mobile layouts stay aligned, but each breakpoint gets deliberate structure instead of a stretched mobile view.',
    },
    workflowSteps: [
      {
        icon: User,
        title: 'Create your account',
        description: 'Start as a patient, provider, or pharmacy partner with role-specific onboarding paths.',
      },
      {
        icon: Calendar,
        title: 'Book or prepare care',
        description: 'Patients schedule care, providers review readiness, and the platform keeps intake details in view.',
      },
      {
        icon: Video,
        title: 'Join secure care delivery',
        description: 'Visits, messaging, and clinical follow-up happen inside the same protected workflow.',
      },
      {
        icon: Pill,
        title: 'Route next steps',
        description: 'Prescriptions, reminders, and fulfillment coordination continue after the visit without context switching.',
      },
    ],
    audienceSection: {
      id: 'network',
      badge: 'Audience Paths',
      title: 'Built for patients, providers, and fulfillment teams.',
      subtitle: 'Each role gets a clear entry point and a premium interface without confusing cross-market language.',
    },
    audienceCards: [
      {
        icon: User,
        tone: 'blue',
        title: 'Patients',
        description: 'Register, book care, manage prescriptions, and keep coverage details ready for future visits.',
        bullets: ['Patient-first primary CTA', 'Visits, messaging, and prescriptions in one place'],
        ctaLabel: 'Create Patient Account',
        ctaHref: '/patient/register',
      },
      {
        icon: Stethoscope,
        tone: 'emerald',
        title: 'Providers',
        description: 'Access schedules, clinical workflows, and secure telehealth tools inside the provider workspace.',
        bullets: ['Clinical workflow access', 'Visit and follow-up continuity'],
        ctaLabel: 'Provider Access',
        ctaHref: '/provider/login',
      },
      {
        icon: Pill,
        tone: 'violet',
        title: 'Pharmacies and operations',
        description: 'Prescription routing and fulfillment visibility remain connected to the rest of the care journey.',
        bullets: ['Prescription queue visibility', 'Operational handoff support'],
        ctaLabel: 'Pharmacy Portal',
        ctaHref: '/pharmacy/login',
      },
    ],
    pricingSection: {
      title: 'Membership options already present in the product',
      subtitle: 'US pricing stays in dollars only, and the section reflects existing subscription tiers instead of placeholder values.',
      note: 'Pay-per-visit and insurance-supported scheduling remain available in the booking flow.',
    },
    plans: [
      {
        eyebrow: 'Docta Basic',
        title: '$19.99',
        period: '/month',
        description: 'Essentials for ongoing care and messaging.',
        tone: 'blue',
        featured: false,
        features: [
          'Unlimited messaging with providers',
          '2 telehealth consultations per month',
          'Prescription access',
          'Health records access',
        ],
        ctaLabel: 'Choose Basic',
        ctaHref: '/patient/register',
      },
      {
        eyebrow: 'Docta Gold',
        title: '$39.99',
        period: '/month',
        description: 'Unlimited consultations with priority access.',
        tone: 'emerald',
        featured: true,
        features: [
          'Unlimited video consultations',
          'Prescription access',
          'Priority support',
          '24/7 urgent care access',
        ],
        ctaLabel: 'Choose Gold',
        ctaHref: '/patient/register',
      },
      {
        eyebrow: 'Docta Platinum',
        title: '$79.99',
        period: '/month',
        description: 'Premium care coordination for ongoing support.',
        tone: 'violet',
        featured: false,
        features: [
          'All Gold features',
          'Dedicated care coordinator',
          'Family coverage for up to 4 members',
          'Premium membership card',
        ],
        ctaLabel: 'Choose Platinum',
        ctaHref: '/patient/register',
      },
    ],
    securitySection: {
      badge: 'Clinical Trust Layer',
      title: 'Security, continuity, and clean operational boundaries stay visible.',
      description:
        'The US homepage speaks only to protected care delivery, secure communication, and e-prescribing with clear operational boundaries across the product.',
      bullets: [
        'Encrypted messaging and data handling',
        'Protected visit and care coordination flows',
        'Prescription handoff visibility',
        'Role-aware operational access',
      ],
    },
    cta: {
      title: 'Start care without the waiting room.',
      description:
        'Patients can register in minutes. Providers can move directly into the clinical workspace with the same premium interface language across desktop, tablet, and mobile.',
      primary: {
        label: 'Get Started',
        href: '/patient/register',
      },
      secondary: {
        label: 'Provider Portal',
        href: '/provider/login',
      },
    },
    footer: {
      description:
        'Modern virtual care, secure messaging, prescriptions, and pharmacy coordination for the US telehealth experience.',
      email: 'info@doctarx.com',
      homeHref: '/',
      columns: [
        {
          title: 'Patients',
          links: [
            { label: 'Book Consultation', href: '/patient/register' },
            { label: 'How It Works', href: '/#workflow' },
            { label: 'Plans', href: '/#pricing' },
            { label: 'Patient Login', href: '/patient/login' },
          ],
        },
        {
          title: 'Providers',
          links: [
            { label: 'Join as Provider', href: '/provider/register' },
            { label: 'Provider Login', href: '/provider/login' },
            { label: 'Security', href: '/hipaa' },
          ],
        },
        {
          title: 'Operations',
          links: [
            { label: 'Pharmacy Portal', href: '/pharmacy/login' },
            { label: 'Contact', href: '/contact' },
          ],
        },
        {
          title: 'Legal',
          links: [
            { label: 'Privacy', href: '/privacy' },
            { label: 'Terms', href: '/terms' },
            { label: 'Accessibility', href: '/accessibility' },
            { label: 'FAQ', href: '/faq' },
          ],
        },
      ],
      badges: [
        { icon: ShieldCheck, label: 'Secure workflows' },
        { icon: Lock, label: 'Encrypted messaging' },
        { icon: Pill, label: 'E-prescribing' },
      ],
      copyright: 'DoctaRx',
    },
  },
  NG: {
    code: 'NG',
    name: 'Nigeria',
    showCountrySelector: false,
    otherMarket: {
      href: '/',
      label: 'US Experience',
    },
    banner: {
      emergencyNumber: '112',
      emergencyLabel: 'Medical emergency? Call',
      emergencyTail: 'or go to the nearest hospital immediately.',
    },
    navLinks: [
      { label: 'Workflow', href: '#workflow' },
      { label: 'Network', href: '#network' },
      { label: 'Pricing', href: '#pricing' },
      { label: 'Compliance', href: '#security' },
    ],
    loginItems: [
      {
        label: 'Sign In',
        description: 'Patient and pharmacy access',
        href: '/ng/auth/login',
        icon: User,
        tone: 'emerald',
      },
      {
        label: 'Provider Portal',
        description: 'Clinical workspace and video visits',
        href: '/ng/provider/login',
        icon: Stethoscope,
        tone: 'blue',
      },
      {
        label: 'Pharmacy Onboarding',
        description: 'Join the prescription network',
        href: '/ng/pharmacy/onboarding',
        icon: Pill,
        tone: 'violet',
      },
    ],
    getStartedItems: [
      {
        label: 'Search Medicines',
        description: 'Compare pharmacy availability',
        href: '/ng/patient/search',
        icon: Search,
        tone: 'emerald',
      },
      {
        label: 'Upload Prescription',
        description: 'Start with your digital Rx',
        href: '/ng/patient/prescriptions',
        icon: Package,
        tone: 'blue',
      },
      {
        label: 'Provider',
        description: 'Join the clinical network',
        href: '/ng/provider/register',
        icon: Stethoscope,
        tone: 'slate',
      },
      {
        label: 'Register Pharmacy',
        description: 'Grow your pharmacy network reach',
        href: '/ng/pharmacy/onboarding',
        icon: Pill,
        tone: 'violet',
      },
    ],
    hero: {
      badge: 'Nigeria care network',
      title: 'Prescription access built around pharmacy fulfillment.',
      highlight: 'Search, route, pay, and deliver inside one premium flow.',
      description:
        'Patients can search medications or upload a prescription, while pharmacies manage verification, pricing, and fulfillment with local payment rails and delivery tracking.',
      primaryCta: {
        label: 'Search Medicines',
        href: '/ng/patient/search',
      },
      secondaryCta: {
        label: 'Upload Prescription',
        href: '/ng/patient/prescriptions',
      },
      tertiaryCta: {
        label: 'Register Pharmacy',
        href: '/ng/pharmacy/onboarding',
      },
      trustItems: [
        { icon: Package, text: 'Prescription upload' },
        { icon: Truck, text: 'Delivery tracking' },
        { icon: CreditCard, text: 'Transfer, card, USSD' },
        { icon: ShieldCheck, text: 'NDPA-aware workflow' },
      ],
      visualTone: 'emerald',
      visual: {
        title: 'Pharmacy-First Network',
        subtitle: 'Patients, pharmacies, pricing, and delivery events move through one regional flow.',
        chips: ['Bank transfer', 'Card', 'USSD'],
        metric: {
          value: 'Operationally local',
          label: 'Medication search, prescription verification, and last-mile delivery stay visible from one dashboard.',
        },
        tiles: [
          {
            title: 'Prescription intake',
            body: 'Search-led and upload-led orders converge into one medication workflow without fake placeholder data.',
            tone: 'emerald',
          },
          {
            title: 'Pharmacy confirmation',
            body: 'Availability, substitutions, and pricing are confirmed by partner pharmacies before checkout.',
            tone: 'blue',
          },
          {
            title: 'Delivery orchestration',
            body: 'Order state, pickup readiness, and last-mile tracking remain visible after payment confirmation.',
            tone: 'violet',
          },
        ],
        railTitle: 'Regional workflow highlights',
        railItems: [
          'Prescription upload or medicine search at entry',
          'Pharmacy-first verification before payment',
          'Delivery status updates and order traceability after checkout',
        ],
      },
    },
    stats: [
      { icon: Search, value: 'Search or upload', label: 'start the patient flow either way' },
      { icon: CreditCard, value: 'Local rails', label: 'transfer, card, and USSD support' },
      { icon: Truck, value: 'Delivery tracking', label: 'pickup and dispatch status visibility' },
      { icon: Building2, value: 'Pharmacy network', label: 'regional operations with premium UX' },
    ],
    featureSection: {
      badge: 'Regional Experience',
      title: 'Nigeria gets the same design quality, tuned for a pharmacy-first model.',
      subtitle:
        'The Nigeria homepage now matches the premium feel of the US experience while staying local in workflow, pricing, and compliance language.',
    },
    features: [
      {
        icon: Package,
        tone: 'emerald',
        preview: 'checkout',
        title: 'Prescription-led entry',
        description: 'Patients can search medications or upload a prescription without landing in a reduced mobile-only shell.',
        points: ['Search-first flow', 'Prescription upload path'],
      },
      {
        icon: Building2,
        tone: 'blue',
        preview: 'pharmacy',
        title: 'Partner pharmacy confirmation',
        description: 'Availability, substitutions, and pricing are presented through pharmacy operations instead of generic placeholder cards.',
        points: ['Inventory-aware status', 'Partner confirmation'],
      },
      {
        icon: Truck,
        tone: 'violet',
        preview: 'delivery',
        title: 'Fulfillment visibility',
        description: 'Patients and pharmacy teams can keep pickup, dispatch, and handoff states readable across every breakpoint.',
        points: ['Delivery states', 'Pickup readiness'],
      },
      {
        icon: CreditCard,
        tone: 'amber',
        preview: 'wallet',
        previewLabels: ['Card', 'Transfer', 'USSD', 'Pickup'],
        title: 'Local payment rails',
        description: 'Nigeria pricing stays in naira and the product surfaces the payment methods local users already expect.',
        points: ['Transfer, card, and USSD', 'No US pricing leakage'],
      },
    ],
    workflowSection: {
      title: 'How the Nigeria workflow now behaves',
      subtitle: 'This is intentionally regional: the experience is premium and responsive, but the business model stays pharmacy-first and market-correct.',
    },
    workflowSteps: [
      {
        icon: Search,
        title: 'Search or upload',
        description: 'Patients can search by medication or begin with a prescription upload from the homepage.',
      },
      {
        icon: Building2,
        title: 'Compare availability',
        description: 'Pharmacy partners confirm stock, pricing, and substitutions before the order advances.',
      },
      {
        icon: CreditCard,
        title: 'Choose payment',
        description: 'Transfer, card, and USSD options stay visible in a locally appropriate checkout story.',
      },
      {
        icon: Truck,
        title: 'Track fulfillment',
        description: 'Pickup readiness and delivery movement remain traceable after the order is confirmed.',
      },
    ],
    audienceSection: {
      id: 'network',
      badge: 'Pharmacy Network',
      title: 'Premium experience for patients, pharmacies, and operations.',
      subtitle: 'Nigeria stays visually first-class while remaining grounded in local workflow realities.',
    },
    audienceCards: [
      {
        icon: User,
        tone: 'emerald',
        title: 'Patients',
        description: 'Search medicines, upload prescriptions, compare availability, and keep order tracking visible from the same polished landing experience.',
        bullets: ['Search-led patient flow', 'Order updates and medication visibility'],
        ctaLabel: 'Search Medicines',
        ctaHref: '/ng/patient/search',
      },
      {
        icon: Pill,
        tone: 'violet',
        title: 'Pharmacies',
        description: 'Receive prescription demand, confirm stock, publish pricing, and handle fulfillment from a regional dashboard mindset.',
        bullets: ['Prescription intake and pricing', 'Network onboarding path'],
        ctaLabel: 'Register Pharmacy',
        ctaHref: '/ng/pharmacy/onboarding',
      },
      {
        icon: Activity,
        tone: 'blue',
        title: 'Operations',
        description: 'Track routing, payment states, and fulfillment readiness without borrowing US telehealth pricing or messaging.',
        bullets: ['Traceable order states', 'Market-correct operations visibility'],
        ctaLabel: 'Sign In',
        ctaHref: '/ng/auth/login',
      },
    ],
    pricingSection: {
      title: 'Nigeria pricing stays local and pharmacy-oriented',
      subtitle: 'The homepage now shows naira only on the Nigeria route and frames commercial tiers around pharmacy operations instead of US memberships.',
      note: 'Patients see medication and delivery pricing confirmed before checkout. Pharmacy plans follow the existing regional configuration.',
    },
    plans: [
      {
        eyebrow: 'Basic',
        title: '\u20A620,000',
        period: '/month',
        description: 'Entry plan for pharmacies joining the digital prescription network.',
        tone: 'emerald',
        featured: false,
        features: [
          'Prescription intake queue',
          'Pricing confirmation workflow',
          'Order readiness updates',
          'Regional pharmacy onboarding',
        ],
        ctaLabel: 'Start Basic',
        ctaHref: '/ng/pharmacy/onboarding',
      },
      {
        eyebrow: 'Standard',
        title: '\u20A650,000',
        period: '/month',
        description: 'Broader operational support for growing partner pharmacies.',
        tone: 'blue',
        featured: true,
        features: [
          'Everything in Basic',
          'Expanded team access',
          'Delivery coordination support',
          'Improved fulfillment analytics',
        ],
        ctaLabel: 'Choose Standard',
        ctaHref: '/ng/pharmacy/onboarding',
      },
      {
        eyebrow: 'Premium',
        title: '\u20A6100,000',
        period: '/month',
        description: 'Advanced operational visibility for high-throughput pharmacy partners.',
        tone: 'violet',
        featured: false,
        features: [
          'Everything in Standard',
          'Higher-volume workflow support',
          'Operational priority handling',
          'Premium partnership onboarding',
        ],
        ctaLabel: 'Choose Premium',
        ctaHref: '/ng/pharmacy/onboarding',
      },
    ],
    securitySection: {
      badge: 'Compliance and Trust',
      title: 'Nigeria keeps premium UX without losing regional correctness.',
      description:
        'The homepage focuses on pharmacy-first operations, local payment rails, and order traceability with no US subscription pricing, no human photography, and no doctor names.',
      bullets: [
        'NDPA-aware data handling',
        'Prescription verification cues',
        'Transfer, card, and USSD payment language',
        'Order and delivery status visibility',
      ],
    },
    cta: {
      title: 'Make medication access feel modern and reliable.',
      description:
        'Patients can begin with search or prescription upload, while pharmacies can join a premium digital network designed specifically for Nigeria.',
      primary: {
        label: 'Search Medicines',
        href: '/ng/patient/search',
      },
      secondary: {
        label: 'Register Pharmacy',
        href: '/ng/pharmacy/onboarding',
      },
    },
    footer: {
      description:
        'A premium Nigeria experience for prescription discovery, pharmacy operations, payment coordination, and fulfillment tracking.',
      email: 'hello@doctarx.ng',
      homeHref: '/ng',
      columns: [
        {
          title: 'Patients',
          links: [
            { label: 'Search Medicines', href: '/ng/patient/search' },
            { label: 'Upload Prescription', href: '/ng/patient/prescriptions' },
            { label: 'Track Orders', href: '/ng/patient/orders' },
            { label: 'Sign In', href: '/ng/auth/login' },
          ],
        },
        {
          title: 'Pharmacies',
          links: [
            { label: 'Register Pharmacy', href: '/ng/pharmacy/onboarding' },
            { label: 'Network View', href: '/ng#network' },
            { label: 'Pricing', href: '/ng#pricing' },
          ],
        },
        {
          title: 'Compliance',
          links: [
            { label: 'Security', href: '/ng#security' },
            { label: 'Privacy', href: '/privacy' },
            { label: 'Terms', href: '/terms' },
          ],
        },
        {
          title: 'Operations',
          links: [
            { label: 'Provider Login', href: '/ng/provider/login' },
            { label: 'Provider Registration', href: '/ng/provider/register' },
            { label: 'Contact', href: '/contact' },
            { label: 'US Experience', href: '/' },
          ],
        },
      ],
      badges: [
        { icon: ShieldCheck, label: 'Secure workflows' },
        { icon: CreditCard, label: 'Local payment rails' },
        { icon: Truck, label: 'Delivery visibility' },
      ],
      copyright: 'DoctaRx Nigeria',
    },
  },
};
