export const MEDICINE_SEARCH_IMAGE_BASE = '/images/ng/medicines';

export const MEDICINE_SEARCH_IMAGES = {
  hero: {
    key: 'hero',
    label: 'Nigeria Medicine Search',
    src: `${MEDICINE_SEARCH_IMAGE_BASE}/medicine-search-hero-abuja-pharmacy.webp`,
    alt: 'A Nigerian patient searches for medicine on a phone while a pharmacist prepares to confirm availability.',
    placement: 'hero',
    relatedSearchTerms: ['medicine', 'pharmacy', 'catalog', 'availability'],
  },
  painFever: {
    key: 'painFever',
    label: 'Fever',
    src: `${MEDICINE_SEARCH_IMAGE_BASE}/quick-search-fever-pain-relief.webp`,
    alt: 'Fever and pain relief medicine search category.',
    placement: 'quick_search',
    category: 'Pain relief and fever',
    relatedSearchTerms: ['fever', 'pain', 'headache', 'paracetamol', 'ibuprofen'],
  },
  antibiotics: {
    key: 'antibiotics',
    label: 'Antibiotics',
    src: `${MEDICINE_SEARCH_IMAGE_BASE}/category-antibiotics-prescription-required.webp`,
    alt: 'Antibiotics category with prescription confirmation reminder.',
    placement: 'category',
    category: 'Antibiotics',
    relatedSearchTerms: ['antibiotic', 'infection', 'amoxicillin', 'azithromycin'],
  },
  antimalarial: {
    key: 'antimalarial',
    label: 'Malaria',
    src: `${MEDICINE_SEARCH_IMAGE_BASE}/quick-search-malaria-medicine.webp`,
    alt: 'Malaria medicine search category for pharmacy confirmation.',
    placement: 'quick_search',
    category: 'Antimalarials',
    relatedSearchTerms: ['malaria', 'antimalarial', 'artemether', 'lumefantrine'],
  },
  bloodPressure: {
    key: 'bloodPressure',
    label: 'Blood Pressure',
    src: `${MEDICINE_SEARCH_IMAGE_BASE}/quick-search-blood-pressure.webp`,
    alt: 'Blood pressure medicine search category.',
    placement: 'quick_search',
    category: 'Blood pressure and cardiovascular',
    relatedSearchTerms: ['blood pressure', 'hypertension', 'heart', 'amlodipine'],
  },
  diabetes: {
    key: 'diabetes',
    label: 'Diabetes',
    src: `${MEDICINE_SEARCH_IMAGE_BASE}/quick-search-diabetes-medicine.webp`,
    alt: 'Diabetes medicine search category.',
    placement: 'quick_search',
    category: 'Diabetes medications',
    relatedSearchTerms: ['diabetes', 'blood sugar', 'metformin', 'insulin'],
  },
  allergy: {
    key: 'allergy',
    label: 'Allergy',
    src: `${MEDICINE_SEARCH_IMAGE_BASE}/quick-search-allergy-medicine.webp`,
    alt: 'Allergy medicine search category.',
    placement: 'quick_search',
    category: 'Allergy medications',
    relatedSearchTerms: ['allergy', 'itching', 'sneezing', 'cetirizine'],
  },
  coughRespiratory: {
    key: 'coughRespiratory',
    label: 'Cough',
    src: `${MEDICINE_SEARCH_IMAGE_BASE}/quick-search-cough-respiratory.webp`,
    alt: 'Cough and respiratory medicine search category.',
    placement: 'quick_search',
    category: 'Cough, cold, and respiratory',
    relatedSearchTerms: ['cough', 'cold', 'catarrh', 'respiratory'],
  },
  asthma: {
    key: 'asthma',
    label: 'Asthma',
    src: `${MEDICINE_SEARCH_IMAGE_BASE}/quick-search-asthma-inhaler.webp`,
    alt: 'Asthma and inhaler medicine search category.',
    placement: 'quick_search',
    category: 'Cough, cold, and respiratory',
    relatedSearchTerms: ['asthma', 'wheezing', 'inhaler', 'salbutamol'],
  },
  ulcerStomach: {
    key: 'ulcerStomach',
    label: 'Ulcer',
    src: `${MEDICINE_SEARCH_IMAGE_BASE}/quick-search-ulcer-stomach.webp`,
    alt: 'Ulcer and stomach medicine search category.',
    placement: 'quick_search',
    category: 'Stomach, ulcer, and digestion',
    relatedSearchTerms: ['ulcer', 'stomach', 'heartburn', 'reflux', 'diarrhea'],
  },
  vitamins: {
    key: 'vitamins',
    label: 'Vitamins',
    src: `${MEDICINE_SEARCH_IMAGE_BASE}/category-vitamins-supplements.webp`,
    alt: 'Vitamins and supplements medicine search category.',
    placement: 'category',
    category: 'Vitamins and supplements',
    relatedSearchTerms: ['vitamin', 'supplement', 'iron', 'zinc', 'calcium'],
  },
  womensHealth: {
    key: 'womensHealth',
    label: "Women's Health",
    src: `${MEDICINE_SEARCH_IMAGE_BASE}/category-womens-health.webp`,
    alt: "Women's health medicine search category.",
    placement: 'category',
    category: "Women's health",
    relatedSearchTerms: ['women', 'contraception', 'vaginal', 'period pain'],
  },
  pediatric: {
    key: 'pediatric',
    label: 'Children',
    src: `${MEDICINE_SEARCH_IMAGE_BASE}/category-pediatric-medicine.webp`,
    alt: 'Pediatric medicine search category for pharmacy confirmation.',
    placement: 'category',
    category: 'Pediatric common medications',
    relatedSearchTerms: ['children', 'child', 'baby', 'syrup', 'pediatric'],
  },
  eyeEar: {
    key: 'eyeEar',
    label: 'Eye & Ear',
    src: `${MEDICINE_SEARCH_IMAGE_BASE}/category-eye-ear-drops.webp`,
    alt: 'Eye and ear drops medicine search category.',
    placement: 'category',
    category: 'Eye, ear, and ENT',
    relatedSearchTerms: ['eye drops', 'ear drops', 'ear', 'eye'],
  },
  skin: {
    key: 'skin',
    label: 'Skin',
    src: `${MEDICINE_SEARCH_IMAGE_BASE}/medicine-skin-dermatology.webp`,
    alt: 'Generic skin and dermatology medicines.',
    placement: 'category',
    category: 'Skin and dermatology',
    relatedSearchTerms: ['skin', 'cream', 'ointment', 'rash', 'fungal'],
  },
  neurology: {
    key: 'neurology',
    label: 'Neurology',
    src: `${MEDICINE_SEARCH_IMAGE_BASE}/medicine-neurology-mental-health.webp`,
    alt: 'Generic neurology and mental health medicine category image.',
    placement: 'category',
    category: 'Mental health and neurological common medicines',
    relatedSearchTerms: ['neurology', 'seizure', 'mental health', 'migraine'],
  },
  hospitalClinic: {
    key: 'hospitalClinic',
    label: 'Clinic Medicines',
    src: `${MEDICINE_SEARCH_IMAGE_BASE}/medicine-hospital-clinic.webp`,
    alt: 'Generic hospital and clinic medicines.',
    placement: 'category',
    category: 'Common hospital and clinic medications',
    relatedSearchTerms: ['injection', 'iv fluid', 'hospital', 'clinic'],
  },
  manualRequest: {
    key: 'manualRequest',
    label: 'Manual Request',
    src: `${MEDICINE_SEARCH_IMAGE_BASE}/manual-medicine-request.webp`,
    alt: 'A patient manually requests medicine availability when search has no exact match.',
    placement: 'manual_request',
    relatedSearchTerms: ['manual', 'request', 'unknown medicine'],
  },
  pharmacyConfirmation: {
    key: 'pharmacyConfirmation',
    label: 'Pharmacy Confirmation',
    src: `${MEDICINE_SEARCH_IMAGE_BASE}/pharmacy-confirmation-workflow.webp`,
    alt: 'A pharmacist reviews a medicine availability request before confirming stock and price.',
    placement: 'confirmation',
    relatedSearchTerms: ['pharmacy', 'confirmation', 'availability', 'price'],
  },
  noExactMatch: {
    key: 'noExactMatch',
    label: 'Manual Request',
    src: `${MEDICINE_SEARCH_IMAGE_BASE}/manual-medicine-request.webp`,
    alt: 'A patient manually requests medicine availability when search has no exact match.',
    placement: 'no_results',
    relatedSearchTerms: ['no result', 'fallback', 'request medicine'],
  },
};

export const QUICK_SEARCH_IMAGE_KEYS = [
  'antimalarial',
  'painFever',
  'coughRespiratory',
  'bloodPressure',
  'diabetes',
  'ulcerStomach',
  'asthma',
  'allergy',
];

export const CATEGORY_IMAGE_KEYS = [
  'antibiotics',
  'vitamins',
  'pediatric',
  'womensHealth',
  'eyeEar',
];
